### ISSUE TITLE
has your paper been published yet? I would like to read about it

### ISSUE THREAD

**Issue by P-ZYang** [AshwinPrksh00/Adapt-FuseNet#3]
Excuse me, has your paper been published yet? I am interested in your code, but I may need a paper to help me understand.

**Comment by AshwinPrksh00** [comment]
Hi PureRua. The paper is in the process of getting published. Meanwhile, you can look at the current predecessor preprint we have on arXiv that documents the methodology
https://arxiv.org/abs/2303.13814
